#!/usr/bin/env python3

# A big thanks to Johannes Pirkl for this patch!

from Xlib import X, protocol
from Xlib.display import Display
import sys

command_number = int(sys.argv[1])

display = Display()
root = display.screen().root

ATOM = display.intern_atom("_PYTYLE_REMOTE")
mask = (X.SubstructureRedirectMask|X.SubstructureNotifyMask)


cm_event = protocol.event.ClientMessage(
    window = root,
    client_type = ATOM,
    data = (32, [command_number,0,0,0,0]))

root.send_event(cm_event,event_mask=mask)
display.flush()
